repository: stefandesu/exo.pm
remote_theme: stefandesu/exo-blog-theme
title: Stefan です
timezone: Europe/Berlin
logo: /images/bowl2_2x.png
email: stefandesu@exo.pm
description: Hi there!
url: https://exo.pm
author: Stefan
github_username:  stefandesu
permalink: pretty
plugins: [jekyll-paginate, jekyll-redirect-from, jekyll-feed, jekyll-seo-tag, jekyll_picture_tag, jekyll-remote-theme]
picture:
  source: "_images"
  output: "assets/img"
paginate: 10
paginate_path: "/page/:num/"
defaults:
 -
   scope:
     path: ""
     type: posts
   values:
     layout: post
 -
   scope:
     path: ""
   values:
     layout: page
navigation:
  -
    name: Home
    url: /
  -
    name: About
    url: /about/
  -
    name: Contact
    url: /contact/
footer: |
  Copyright ©2024 Stefan. [Impressum](/impressum/).
  <br>Logo made by my flatmate Salo. Thanks. :3
feed:
  posts_limit: 20
